apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: tc
  name: tc
spec:
  containers:
  - image: blessedrebus/tc:tc
    name: tc
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
