apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-02-14T14:02:50Z"
  labels:
    run: tc
  name: tc
  namespace: default
  resourceVersion: "198676"
  uid: c8d485e6-c4e3-4097-af3d-f7721217975f
spec:
  clusterIP: 10.106.121.180
  clusterIPs:
  - 10.106.121.180
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 1234
    protocol: TCP
    targetPort: 5000
  selector:
    run: tc
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
