apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: splist
  name: splist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: splist
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: splist
    spec:
      containers:
      - image: blessedrebus/sp:list
        name: splist
        env:
          - name: SERVER_THRESHOLD
            valueFrom:
              configMapKeyRef:
                name: trust-configuration
                key: threshold
        ports:
        - containerPort: 5000
        resources: {}
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: idplist
  name: idplist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: idplist
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: idplist
    spec:
      containers:
      - image: blessedrebus/idp:list
        name: idplist
        ports:
        - containerPort: 3000
        resources: {}
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: tclist
  name: tclist
spec:
  containers: 
  - image: blessedrebus/tc:list
    name: tclist
    env:
    - name: TRUSTED_SERVERS
      valueFrom:
        configMapKeyRef:
          name: trust-configuration
          key: trusted-servers
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: tslist1
  name: tslist1
spec:
  containers:
  - image: blessedrebus/ts:list
    name: tslist1
    env:
    - name: SERVER_PORT
      value: "5000"
    - name: SERVER_NUMBER
      value: "1"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: tslist2
  name: tslist2
spec:
  containers:
  - image: blessedrebus/ts:list
    name: tslist2
    env:
    - name: SERVER_PORT
      value: "6000"
    - name: SERVER_NUMBER
      value: "2"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: tslist3
  name: tslist3
spec:
  containers:
  - image: blessedrebus/ts:list
    name: tslist3
    env:
    - name: SERVER_PORT
      value: "7000"
    - name: SERVER_NUMBER
      value: "3"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-02-14T14:02:34Z"
  labels:
    app: idplist
  name: idplist
  namespace: default
  resourceVersion: "198654"
  uid: b48ce977-f9dc-423c-97c9-e1546883e90e
spec:
  clusterIP: 10.106.13.126
  clusterIPs:
  - 10.106.13.126
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: idplist
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-02-14T14:02:42Z"
  labels:
    app: splist
  name: splist
  namespace: default
  resourceVersion: "198666"
  uid: d302530e-439a-49f0-987d-c31c0e961747
spec:
  clusterIP: 10.111.225.45
  clusterIPs:
  - 10.111.225.45
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 1111
    protocol: TCP
    targetPort: 1111
  selector:
    app: splist
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-02-14T14:02:50Z"
  labels:
    run: tclist
  name: tclist
  namespace: default
  resourceVersion: "198676"
  uid: c8d485e6-c4e3-4097-af3d-f7721217975f
spec:
  clusterIP: 10.106.121.180
  clusterIPs:
  - 10.106.121.180
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 1234
    protocol: TCP
    targetPort: 5000
  selector:
    run: tclist
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-02-14T14:03:00Z"
  labels:
    run: tslist1
  name: tslist1
  namespace: default
  resourceVersion: "198685"
  uid: 54d1efa2-1085-47d2-ab59-bf5f7a0da4d6
spec:
  clusterIP: 10.108.69.38
  clusterIPs:
  - 10.108.69.38
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: tslist1
    protocol: TCP
    port: 5000
    targetPort: 5000
  selector:
    run: tslist1
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-02-14T14:03:00Z"
  labels:
    run: tslist2
  name: tslist2
  namespace: default
  resourceVersion: "198685"
  uid: 54d1efa2-1085-47d2-ab59-bf5f7a0da4d6
spec:
  clusterIP: 10.108.69.39
  clusterIPs:
  - 10.108.69.39
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: tslist2
    protocol: TCP
    port: 6000
    targetPort: 5000
  selector:
    run: tslist2
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-02-14T14:03:00Z"
  labels:
    run: tslist3
  name: tslist3
  namespace: default
  resourceVersion: "198685"
  uid: 54d1efa2-1085-47d2-ab59-bf5f7a0da4d6
spec:
  clusterIP: 10.108.69.40
  clusterIPs:
  - 10.108.69.40
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: tslist3
    protocol: TCP
    port: 7000
    targetPort: 5000
  selector:
    run: tslist3
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}